### ISSUE TITLE
Text File Format for Rooms.

### ISSUE THREAD

**Issue by kerickso** [Arctem/game_jam_2015#1]
Working on a way to format a text file and python script that will turn the text into a room class.

**Comment by Arctem** [comment]
Re your commit: I would prefer one character (or double character) for separating categories and a different one for separating within a category. Based on your example, I would prefer:
room_name:keyword_0;keyword_1;...keyword_n:'room description':'room short description'
We don't need anything to indicate end of line, since we have \n.

**Comment by kerickso** [comment]
Okay, I can do that!

**Comment by Arctem** [comment]
Give me a moment to make a full format for you including the fully updated attributes and stuff.

**Comment by Arctem** [comment]
The one for rooms is pushed and is [here](file_format_ex.txt). Working on others at the moment.

**Comment by Arctem** [comment]
Full format is pushed and is [here](file_format_ex.md). Now with minor formatting! Yay!
